#!/bin/bash

set -eu

yarn
yarn build
yarn lint

[ -f .env ] && source .env

mkdir -p var

env \
      "HUE_BRIDGE_IP_ADDRESS=$HUE_BRIDGE_IP_ADDRESS" \
      "HUE_USERNAME=$HUE_USERNAME" \
      yarn start
